spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.110.20.20:3306/cloud_ops_init
        username: root
        password: 123456a?
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
logging:
    file: /var/log/cloud-ops.log
    level:
        com.cloud.ops: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
cloud-ops:
    file:
        topology: /opt/iop-ops/topology
        package: /opt/iop-ops/package
        remote: /opt/iop-ops/artifact